const columns = [
    {
        key: "fullName",
        name: "Full Name",
        sortable: true,
    },
    {
        key: "address",
        name: "Address",
        sortable: true,
    },
    // {
    //     key: "email",
    //     name: "Email",
    //     sortable: true,
    // },
    {
        key: "phone",
        name: "Phone",
        sortable: true,
    },
    {
        key: "apartmentName",
        name: "Apartment",
        sortable: true,
    },
    {
        key: "complexName",
        name: "Complex",
        sortable: true,
    },
    {
        key: "actions",
        name: "Actions",
    }
]

const tenets = [
    {
        id: 1, 
        fullName: "John Doe",
        firstName: "John",
        lastName: "Doe",
        address: "123 Main St",
        apartmentName: "Apartment 1",
        apartmentId: 1,
        complexName: "Complex 1",
        complexId: 1,
        email: "qKu2S@example.com",
        phone: "123-456-7890",
        createdAt: "2022-01-01",
        modifiedAt: "2022-02-01",
    },
    {
        id: 2, 
        fullName: "Jane Smith",
        firstName: "Jane",
        lastName: "Smith",
        address: "456 Oak Ave",
        apartmentName: "Apartment 2",
        apartmentId: 2,
        complexName: "Complex 2",
        complexId: 2,
        email: "9zKmZ@example.com",
        phone: "987-654-3210",
        createdAt: "2022-01-15",
        modifiedAt: "2022-02-15",
    },
    {
        id: 3, 
        fullName: "Bob Johnson",
        firstName: "Bob",
        lastName: "Johnson",
        address: "789 Pine St",
        apartmentName: "Apartment 3",
        apartmentId: 3,
        complexName: "Complex 3",
        complexId: 3,
        email: "bLb9H@example.com",
        phone: "555-555-5555",
        createdAt: "2022-02-01",
        modifiedAt: "2022-03-01",
    },
    {
        id: 4, 
        fullName: "Sarah Lee",
        firstName: "Sarah",
        lastName: "Lee",
        address: "321 Elm St",
        apartmentName: "Apartment 4",
        apartmentId: 4,
        complexName: "Complex 4",
        complexId: 4,
        email: "5tqFP@example.com",
        phone: "111-222-3333",
        createdAt: "2022-03-01",
        modifiedAt: "2022-04-01",
    },
    {
        id: 5, 
        fullName: "Mike Brown",
        firstName: "Mike",
        lastName: "Brown",
        address: "987 Pine St",
        apartmentName: "Apartment 5",
        apartmentId: 5,
        complexName: "Complex 5",
        complexId: 5,
        email: "bLb9H@example.com",
        phone: "555-555-5555",
        createdAt: "2022-02-01",
        modifiedAt: "2022-03-01",
    },
    {
        id: 6, 
        fullName: "Emily Johnson",
        firstName: "Emily",
        lastName: "Johnson",
        address: "456 Oak Ave",
        apartmentName: "Apartment 6",
        apartmentId: 6,
        complexName: "Complex 6",
        complexId: 6,
        email: "9zKmZ@example.com",
        phone: "987-654-3210",
        createdAt: "2022-01-15",
        modifiedAt: "2022-02-15",
    },
    {
        id: 7, 
        fullName: "David Kim",
        firstName: "David",
        lastName: "Kim",
        address: "123 Main St",
        apartmentName: "Apartment 7",
        apartmentId: 7,
        complexName: "Complex 7",
        complexId: 7,
        email: "qKu2S@example.com",
        phone: "123-456-7890",
        createdAt: "2022-01-01",
        modifiedAt: "2022-02-01",
    },
    {
        id: 8, 
        fullName: "Jessica Chen",
        firstName: "Jessica",
        lastName: "Chen",
        address: "789 Pine St",
        apartmentName: "Apartment 8",
        apartmentId: 8,
        complexName: "Complex 8",
        complexId: 8,
        email: "bLb9H@example.com",
        phone: "555-555-5555",
        createdAt: "2022-02-01",
        modifiedAt: "2022-03-01",
    },
    {
        id: 9, 
        fullName: "Alex Kim",
        firstName: "Alex",
        lastName: "Kim",
        address: "321 Elm St",
        apartmentName: "Apartment 9",
        apartmentId: 9,
        complexName: "Complex 9",
        complexId: 9,
        email: "5tqFP@example.com",
        phone: "111-222-3333",
        createdAt: "2022-03-01",
        modifiedAt: "2022-04-01",
    },
    {
        id: 10, 
        fullName: "Olivia Chen",
        firstName: "Olivia",
        lastName: "Chen",
        address: "987 Pine St",
        apartmentName: "Apartment 10",
        apartmentId: 10,
        complexName: "Complex 10",
        complexId: 10,
        email: "bLb9H@example.com",
        phone: "555-555-5555",
        createdAt: "2022-02-01",
        modifiedAt: "2022-03-01",
    },
    {
        id: 11, 
        fullName: "Michael Smith",
        firstName: "Michael",
        lastName: "Smith",
        address: "456 Oak Ave",
        apartmentName: "Apartment 11",
        apartmentId: 11,
        complexName: "Complex 11",
        complexId: 11,
        email: "9zKmZ@example.com",
        phone: "987-654-3210",
        createdAt: "2022-01-15",
        modifiedAt: "2022-02-15",
    },
    {
        id: 12, 
        fullName: "Emily Johnson",
        firstName: "Emily",
        lastName: "Johnson",
        address: "123 Main St",
        apartmentName: "Apartment 12",
        apartmentId: 12,
        complexName: "Complex 12",
        complexId: 12,
        email: "qKu2S@example.com",
        phone: "123-456-7890",
        createdAt: "2022-01-01",
        modifiedAt: "2022-02-01",
    }

]

export {tenets, columns}